import jsPDF from 'jspdf'
import { format, parseISO } from 'date-fns'
import type { BehaviourFunction, ProtectiveFactor } from '@/lib/types'

const LINE_HEIGHT = 6
const BODY_FONT = 10
const HEADING_FONT = 14
const TITLE_FONT = 20

function createPdfHelper() {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  const maxWidth = pageWidth - margin * 2
  let y = 20
  let footerFn: (() => void) | null = null

  const setFooter = (fn: () => void) => { footerFn = fn }

  const addFooter = () => {
    if (footerFn) footerFn()
  }

  const checkPageBreak = (needed: number) => {
    const pageHeight = doc.internal.pageSize.getHeight()
    if (y + needed > pageHeight - 25) {
      addFooter()
      doc.addPage()
      y = 20
    }
  }

  const addWrappedText = (text: string, fontSize = BODY_FONT, fontStyle: 'normal' | 'bold' | 'italic' = 'normal') => {
    doc.setFontSize(fontSize)
    doc.setFont('helvetica', fontStyle)
    const wrapped = doc.splitTextToSize(text, maxWidth)
    checkPageBreak(wrapped.length * LINE_HEIGHT)
    doc.text(wrapped, margin, y)
    y += wrapped.length * LINE_HEIGHT
  }

  return { doc, pageWidth, margin, maxWidth, getY: () => y, setY: (v: number) => { y = v }, addY: (v: number) => { y += v }, checkPageBreak, addWrappedText, addFooter, setFooter }
}

/** Render a markdown-ish line with basic bold/italic/bullet support */
function renderMarkdownLine(
  doc: jsPDF,
  line: string,
  margin: number,
  maxWidth: number,
  y: number,
  checkPageBreak: (n: number) => void
): number {
  // Bullet points
  const bulletMatch = line.match(/^(\s*[-*]\s+)(.*)/)
  const isBullet = !!bulletMatch
  const bulletIndent = isBullet ? 8 : 0
  const text = isBullet ? bulletMatch![2] : line

  // Strip markdown bold/italic markers for PDF (jsPDF can't mix inline styles)
  const cleaned = text
    .replace(/\*\*\*(.+?)\*\*\*/g, '$1')
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/\*(.+?)\*/g, '$1')
    .replace(/_(.+?)_/g, '$1')

  // Detect if entire line is bold
  const isBold = /^\*\*[^*]+\*\*$/.test(text.trim()) || /^__[^_]+__$/.test(text.trim())

  doc.setFontSize(BODY_FONT)
  doc.setFont('helvetica', isBold ? 'bold' : 'normal')

  const effectiveWidth = maxWidth - bulletIndent
  const wrapped = doc.splitTextToSize(cleaned, effectiveWidth)
  checkPageBreak(wrapped.length * LINE_HEIGHT)

  if (isBullet) {
    doc.text('\u2022', margin, y)
  }
  doc.text(wrapped, margin + bulletIndent, y)
  y += wrapped.length * LINE_HEIGHT

  doc.setFont('helvetica', 'normal')
  return y
}

export function exportAnalysisPdf(
  initials: string,
  dateFrom: string,
  dateTo: string,
  incidentCount: number,
  content: string
) {
  const { doc, pageWidth, margin, maxWidth, getY, setY, addY, checkPageBreak, addFooter, setFooter } = createPdfHelper()

  setFooter(() => {
    const pageHeight = doc.internal.pageSize.getHeight()
    doc.setFontSize(8)
    doc.setTextColor(100)
    doc.text('Generated by PBS Lens', margin, pageHeight - 10)
    doc.text(format(new Date(), 'dd/MM/yyyy HH:mm'), pageWidth - margin, pageHeight - 10, { align: 'right' })
    doc.setTextColor(0)
  })

  // Header
  doc.setFontSize(TITLE_FONT)
  doc.setFont('helvetica', 'bold')
  doc.text(initials, margin, getY())
  addY(8)
  doc.setFontSize(BODY_FONT)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100)
  doc.text(
    `${format(parseISO(dateFrom), 'dd MMM yyyy')} – ${format(parseISO(dateTo), 'dd MMM yyyy')} · ${incidentCount} incidents`,
    margin, getY()
  )
  doc.setTextColor(0)
  addY(12)

  // Parse markdown content
  const lines = content.split('\n')
  for (const line of lines) {
    if (line.startsWith('## ')) {
      checkPageBreak(18)
      addY(6)
      doc.setFontSize(HEADING_FONT)
      doc.setFont('helvetica', 'bold')
      const wrapped = doc.splitTextToSize(line.replace('## ', ''), maxWidth)
      doc.text(wrapped, margin, getY())
      setY(getY() + wrapped.length * 7 + 4)
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(BODY_FONT)
    } else if (line.trim() === '') {
      addY(4)
    } else {
      const newY = renderMarkdownLine(doc, line, margin, maxWidth, getY(), checkPageBreak)
      setY(newY)
    }
  }

  addFooter()
  doc.save(`${initials}-analysis-${dateFrom}-to-${dateTo}.pdf`)
}

export interface FbaRow {
  behaviourCode: string
  behaviourLabel: string
  functions: string
  primaryAntecedents: string[]
  primaryConsequences: string[]
  frequency: number
  trend: string
}

export function exportFbaSummaryPdf(
  initials: string,
  rows: FbaRow[],
  organisation?: string
) {
  const { doc, pageWidth, margin, getY, setY, addY, checkPageBreak, addFooter, setFooter } = createPdfHelper()

  setFooter(() => {
    const pageHeight = doc.internal.pageSize.getHeight()
    doc.setFontSize(8)
    doc.setTextColor(100)
    const footerY = organisation ? pageHeight - 14 : pageHeight - 10
    doc.text('Generated by PBS Lens', margin, footerY)
    doc.text(format(new Date(), 'dd/MM/yyyy HH:mm'), pageWidth - margin, footerY, { align: 'right' })
    if (organisation) {
      doc.text(organisation, margin, pageHeight - 9)
    }
    doc.setTextColor(0)
  })

  // Title
  doc.setFontSize(TITLE_FONT)
  doc.setFont('helvetica', 'bold')
  doc.text(`${initials} — Functional Behaviour Assessment Summary`, margin, getY())
  addY(8)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100)
  doc.text(`Generated ${format(new Date(), 'dd MMMM yyyy')}`, margin, getY())
  doc.setTextColor(0)
  addY(10)

  // Table
  const colWidths = [28, 32, 34, 34, 18, 22]
  const headers = ['Behaviour', 'Function', 'Antecedents', 'Consequences', 'Freq.', 'Trend']
  const tableWidth = colWidths.reduce((a, b) => a + b, 0)
  const startX = margin

  // Header row
  const headerHeight = 8
  doc.setFillColor(240, 240, 240)
  doc.rect(startX, getY() - 5, tableWidth, headerHeight, 'F')
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  let hx = startX + 2
  for (let i = 0; i < headers.length; i++) {
    doc.text(headers[i], hx, getY())
    hx += colWidths[i]
  }
  addY(headerHeight)

  // Data rows
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7.5)

  for (const row of rows) {
    const cellTexts = [
      row.behaviourLabel,
      row.functions,
      row.primaryAntecedents.join(', '),
      row.primaryConsequences.join(', '),
      String(row.frequency),
      row.trend,
    ]

    // Calculate row height based on wrapped text
    let maxLines = 1
    const wrappedCells: string[][] = []
    for (let i = 0; i < cellTexts.length; i++) {
      const wrapped = doc.splitTextToSize(cellTexts[i], colWidths[i] - 4)
      wrappedCells.push(wrapped)
      if (wrapped.length > maxLines) maxLines = wrapped.length
    }
    const rowHeight = maxLines * 4 + 4

    checkPageBreak(rowHeight + 2)

    // Draw row border
    doc.setDrawColor(220, 220, 220)
    doc.rect(startX, getY() - 4, tableWidth, rowHeight)

    // Draw cell text
    let cx = startX + 2
    for (let i = 0; i < wrappedCells.length; i++) {
      doc.text(wrappedCells[i], cx, getY())
      cx += colWidths[i]
    }

    setY(getY() + rowHeight - 2)
  }

  addFooter()
  doc.save(`${initials}-fba-summary.pdf`)
}

export interface PbsPlanPdfData {
  enjoys?: string | null
  important_to?: string | null
  good_at?: string | null
  helps_relax?: string | null
  personal_risk_factors?: string | null
  environmental_risk_factors?: string | null
  slow_triggers?: string | null
  fast_triggers?: string | null
  behaviour_functions?: BehaviourFunction[]
  protective_factors?: ProtectiveFactor[]
  proactive_strategies?: string | null
  active_strategies?: string | null
  reactive_strategies?: string | null
}

export function exportPbsPlanPdf(
  initials: string,
  plan: PbsPlanPdfData,
  organisation?: string
) {
  const { doc, pageWidth, margin, maxWidth, getY, setY, addY, checkPageBreak, addFooter, setFooter, addWrappedText } = createPdfHelper()

  setFooter(() => {
    const pageHeight = doc.internal.pageSize.getHeight()
    doc.setFontSize(8)
    doc.setTextColor(100)
    const footerY = organisation ? pageHeight - 14 : pageHeight - 10
    doc.text('Generated by PBS Lens', margin, footerY)
    doc.text(format(new Date(), 'dd/MM/yyyy HH:mm'), pageWidth - margin, footerY, { align: 'right' })
    if (organisation) {
      doc.text(organisation, margin, pageHeight - 9)
    }
    doc.setTextColor(0)
  })

  const addSection = (title: string, content: string | null | undefined) => {
    if (!content) return
    checkPageBreak(20)
    addY(4)
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text(title, margin, getY())
    addY(7)
    doc.setFontSize(BODY_FONT)
    doc.setFont('helvetica', 'normal')
    const wrapped = doc.splitTextToSize(content, maxWidth)
    checkPageBreak(wrapped.length * LINE_HEIGHT)
    doc.text(wrapped, margin, getY())
    setY(getY() + wrapped.length * LINE_HEIGHT + 4)
  }

  // Title
  doc.setFontSize(TITLE_FONT)
  doc.setFont('helvetica', 'bold')
  doc.text(`${initials} — PBS Plan`, margin, getY())
  addY(12)

  // Person-Centred Profile
  addSection('Enjoys', plan.enjoys)
  addSection('Important To', plan.important_to)
  addSection('Good At', plan.good_at)
  addSection('Helps Relax', plan.helps_relax)

  // Risk Factors
  addSection('Personal Risk Factors', plan.personal_risk_factors)
  addSection('Environmental Risk Factors', plan.environmental_risk_factors)

  // Triggers
  addSection('Slow Triggers', plan.slow_triggers)
  addSection('Fast Triggers', plan.fast_triggers)

  // Behaviour Functions
  if (plan.behaviour_functions && plan.behaviour_functions.length > 0) {
    checkPageBreak(20)
    addY(4)
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text('Behaviour Functions', margin, getY())
    addY(8)

    for (const bf of plan.behaviour_functions) {
      checkPageBreak(30)
      doc.setFontSize(11)
      doc.setFont('helvetica', 'bold')
      doc.text(bf.name || 'Unnamed Function', margin, getY())
      addY(LINE_HEIGHT)

      if (bf.description) {
        doc.setFontSize(BODY_FONT)
        doc.setFont('helvetica', 'italic')
        const descWrapped = doc.splitTextToSize(bf.description, maxWidth)
        checkPageBreak(descWrapped.length * LINE_HEIGHT)
        doc.text(descWrapped, margin, getY())
        setY(getY() + descWrapped.length * LINE_HEIGHT)
      }

      if (bf.primary_function) {
        doc.setFontSize(BODY_FONT)
        doc.setFont('helvetica', 'normal')
        addWrappedText(`Primary: ${bf.primary_function}`)
      }
      if (bf.secondary_function) {
        addWrappedText(`Secondary: ${bf.secondary_function}`)
      }
      addY(4)
    }
  }

  // Protective Factors
  if (plan.protective_factors && plan.protective_factors.length > 0) {
    checkPageBreak(20)
    addY(4)
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text('Protective Factors', margin, getY())
    addY(8)

    for (const pf of plan.protective_factors) {
      checkPageBreak(25)
      doc.setFontSize(11)
      doc.setFont('helvetica', 'bold')
      doc.text(pf.title || 'Unnamed Factor', margin, getY())
      addY(LINE_HEIGHT)

      if (pf.description) {
        addWrappedText(pf.description)
      }
      if (pf.how_to_use) {
        doc.setFontSize(BODY_FONT)
        doc.setFont('helvetica', 'italic')
        const howWrapped = doc.splitTextToSize(`How to use: ${pf.how_to_use}`, maxWidth)
        checkPageBreak(howWrapped.length * LINE_HEIGHT)
        doc.text(howWrapped, margin, getY())
        setY(getY() + howWrapped.length * LINE_HEIGHT)
        doc.setFont('helvetica', 'normal')
      }
      addY(4)
    }
  }

  // Intervention Strategies
  addSection('Proactive Strategies', plan.proactive_strategies)
  addSection('Active Strategies', plan.active_strategies)
  addSection('Reactive Strategies', plan.reactive_strategies)

  addFooter()
  doc.save(`${initials}-pbs-plan.pdf`)
}
