import jsPDF from 'jspdf'
import { format } from 'date-fns'

export function exportAnalysisPdf(
  initials: string,
  dateFrom: string,
  dateTo: string,
  incidentCount: number,
  content: string
) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  const maxWidth = pageWidth - margin * 2
  let y = 20

  const addFooter = () => {
    const pageHeight = doc.internal.pageSize.getHeight()
    doc.setFontSize(8)
    doc.setTextColor(100)
    doc.text('Generated by PBS Lens', margin, pageHeight - 10)
    doc.text(format(new Date(), 'dd/MM/yyyy HH:mm'), pageWidth - margin, pageHeight - 10, { align: 'right' })
    doc.setTextColor(0)
  }

  const checkPageBreak = (needed: number) => {
    const pageHeight = doc.internal.pageSize.getHeight()
    if (y + needed > pageHeight - 20) {
      addFooter()
      doc.addPage()
      y = 20
    }
  }

  // Header
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text(initials, margin, y)
  y += 8
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100)
  doc.text(
    `${format(new Date(dateFrom), 'dd MMM yyyy')} – ${format(new Date(dateTo), 'dd MMM yyyy')} · ${incidentCount} incidents`,
    margin, y
  )
  doc.setTextColor(0)
  y += 12

  // Parse markdown content
  const lines = content.split('\n')
  for (const line of lines) {
    if (line.startsWith('## ')) {
      checkPageBreak(15)
      y += 6
      doc.setFontSize(14)
      doc.setFont('helvetica', 'bold')
      const wrapped = doc.splitTextToSize(line.replace('## ', ''), maxWidth)
      doc.text(wrapped, margin, y)
      y += wrapped.length * 6 + 4
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(10)
    } else if (line.trim() === '') {
      y += 4
    } else {
      const wrapped = doc.splitTextToSize(line, maxWidth)
      checkPageBreak(wrapped.length * 5)
      doc.text(wrapped, margin, y)
      y += wrapped.length * 5
    }
  }

  addFooter()
  doc.save(`${initials}-analysis-${dateFrom}-to-${dateTo}.pdf`)
}

export function exportPbsPlanPdf(
  initials: string,
  plan: Record<string, unknown>
) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  const maxWidth = pageWidth - margin * 2
  let y = 20

  const addFooter = () => {
    const pageHeight = doc.internal.pageSize.getHeight()
    doc.setFontSize(8)
    doc.setTextColor(100)
    doc.text('Generated by PBS Lens', margin, pageHeight - 10)
    doc.setTextColor(0)
  }

  const checkPageBreak = (needed: number) => {
    const pageHeight = doc.internal.pageSize.getHeight()
    if (y + needed > pageHeight - 20) {
      addFooter()
      doc.addPage()
      y = 20
    }
  }

  const addSection = (title: string, content: string | null) => {
    if (!content) return
    checkPageBreak(20)
    y += 4
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text(title, margin, y)
    y += 7
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    const wrapped = doc.splitTextToSize(content, maxWidth)
    checkPageBreak(wrapped.length * 5)
    doc.text(wrapped, margin, y)
    y += wrapped.length * 5 + 4
  }

  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text(`${initials} — PBS Plan`, margin, y)
  y += 12

  addSection('Enjoys', plan.enjoys as string | null)
  addSection('Important To', plan.important_to as string | null)
  addSection('Good At', plan.good_at as string | null)
  addSection('Helps Relax', plan.helps_relax as string | null)
  addSection('Personal Risk Factors', plan.personal_risk_factors as string | null)
  addSection('Environmental Risk Factors', plan.environmental_risk_factors as string | null)
  addSection('Slow Triggers', plan.slow_triggers as string | null)
  addSection('Fast Triggers', plan.fast_triggers as string | null)
  addSection('Proactive Strategies', plan.proactive_strategies as string | null)
  addSection('Active Strategies', plan.active_strategies as string | null)
  addSection('Reactive Strategies', plan.reactive_strategies as string | null)

  addFooter()
  doc.save(`${initials}-pbs-plan.pdf`)
}
